[project]
name = "ai-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faiss-cpu>=1.13.2",
    "fastapi>=0.128.0",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.1.7",
    "uvicorn>=0.40.0",
]
